name: Upload to Replay
author: Replay.io
description: Uploads recordings to Replay.io
inputs:
  apiKey:
    required: true
    description: "Replay.io API Key"
  filter:
    description: "A JSONata function to pass to `$filter` to select replays to upload"
  public:
    description: "Makes the uploaded replay viewable by everyone"
    default: false
outputs:
  recordings:
    description: "Array of recordings uploaded"
    value: ${{ steps.upload-recordings.outputs.result }}
runs:
  using: composite
  steps:
    - name: 'Upload Recordings'
      id: 'upload-recordings'
      uses: actions/github-script@v6
      with:
        result-encoding: json
        script: |
          const upload = require(process.env.GITHUB_ACTION_PATH + '/dist/upload.js');
          const ids = await upload({
            apiKey: '${{ inputs.apiKey || null }}',
            public: ${{ inputs.public || false }},
            filter: '${{ inputs.filter || null }}'
          });
          return ids;
      env:
        RECORD_REPLAY_API_KEY: ${{ inputs.apiKey }}