name: Upload to Replay
author: Replay.io
description: Uploads recordings to Replay.io
inputs:
  apiKey:
    required: true
    description: "Replay.io API Key"
  filter:
    description: "A JSONata function to pass to `$filter` to select replays to upload"
  public:
    description: "Makes the uploaded replay viewable by everyone"
    default: false
  cli-version:
    description: "Version of @replayio/replay to use"
    default: latest
outputs:
  recordings:
    description: "Array of recordings uploaded"
    value: ${{ steps.upload-recordings.outputs.result }}
runs:
  using: composite
  steps:
    - name: 'Install Replay CLI'
      run: npm i --prefix $GITHUB_ACTION_PATH @replayio/replay@${{ inputs.cli-version }}
      shell: sh
    - name: 'Upload Recordings'
      id: 'upload-recordings'
      uses: actions/github-script@v6
      with:
        result-encoding: json
        script: |
          const cliPath = '/node_modules/@replayio/replay';
          const cli = require(process.env.GITHUB_ACTION_PATH + cliPath);
          const { source } = require(process.env.GITHUB_ACTION_PATH + cliPath + "/metadata");
          const upload = require(process.env.GITHUB_ACTION_PATH + '/dist/upload.js');
          const metadata = process.env.GITHUB_SHA && source.init({
            branch: process.env.GITHUB_REF_NAME,
            commit: {
              id: process.env.GITHUB_SHA,
              title: '${{ github.event.commits[0].message }}'
            },
            merge: ${{ github.event.issue.number || 'undefined' }} && {
              id: '${{ github.event.issue.number }}',
              title: '${{ github.event.issue.title }}'
            },
            provider: 'github',
            repository: process.env.GITHUB_REPOSITORY
          });
          const ids = await upload({
            cli,
            apiKey: '${{ inputs.apiKey || null }}',
            public: ${{ inputs.public || false }},
            filter: '${{ inputs.filter || null }}',
            metadata
          });
          return ids;
      env:
        RECORD_REPLAY_API_KEY: ${{ inputs.apiKey }}